---
name: test

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout@scm
        uses: actions/checkout@main

      - name: setup@kindconfig
        run: |
          kind_in="${{ github.workspace }}/.github/config/kind.yml.in"
          kind_out="${{ github.workspace }}/.github/config/kind.yml"
          hostip=$(sh .github/scripts/get-host-ip.sh)
          sed "s/127.0.0.1/$hostip/g" $kind_in > $kind_out

      - name: setup@kubernetes
        uses: engineerd/setup-kind@v0.5.0
        with:
          config: .github/config/kind.yml

      - name: setup@kubeconfig
        run: |
          hostip=$(sh .github/scripts/get-host-ip.sh)
          sed "s/127.0.0.1/$hostip/g" $HOME/.kube/config > ${{ github.workspace }}/kubeconfig.yml

      - name: run@klifter
        uses: ./klifter
        with:
          path: tests
          kubeconfig: kubeconfig.yml

      - name: test@klifter
        run: |
          kubectl get serviceaccounts foo
          kubectl get serviceaccounts bar

      - name: run@klander
        uses: ./klander
        with:
          kubeconfig: kubeconfig.yml

      - name: test@klander
        run: |
          kubectl get serviceaccounts foo
          ! kubectl get serviceaccounts bar
